mindbox-cloud/react-native-sdk

README.md
android/src/main/java/com/mindboxsdk/MindboxSdkModule.kt
ios/MindboxSdk.m
ios/MindboxSdk.swift
src/index.tsx

Ticket - [95](https://github.com/mindbox-moscow/issues-mobile-sdk/issues/95)
- Basic SDK configuration
- Add initialize method
- Add getDeviceUUID method
- Add getToken method
- Add updateToken method

95 configure sdk and create initialization methods

---

CHANGELOG.md
README.md
android/src/main/java/com/mindboxsdk/MindboxSdkModule.kt
ios/MindboxSdk.m
ios/MindboxSdk.swift
src/__tests__/index.test.ts
src/index.tsx

Add executeAsyncOperation public method

feat: add executeAsyncOperation method

---

ios/MindboxJsDelivery.m

Changes:
- Add support for old push notifications format

Old push notifications format support

---

package.json
src/index.tsx

Add removeOnPushClickReceived method

Add removeOnPushClickReceived method

---

android/src/main/java/com/mindboxsdk/MindboxJsDelivery.kt
ios/MindboxJsDelivery.m
src/index.tsx

Add pushPayload argument to onPushClickReceived method's callback.

Add payload argument to onPushClickReceived

---

CHANGELOG.md
MindboxSdk.podspec
android/build.gradle
android/src/main/java/com/mindboxsdk/MindboxJsDelivery.kt
android/src/main/java/com/mindboxsdk/MindboxSdkModule.kt
example/android/app/src/main/AndroidManifest.xml
example/android/build.gradle
ios/MindboxJsDelivery.m
package.json
src/index.tsx

- upgrade iOS SDK dependency to v2.0.1
- upgrade Android SDK dependency to v2.1.1
- add support of Huawei Push Kit
- update onPushClickReceived method: add second argument with push payload 
- add removeOnPushClickReceived method

Huawei support

---

CHANGELOG.md
android/build.gradle
package.json

Upgrade mindbox mobile-sdk to v2.1.2

Upgrade mindbox mobile-sdk to v2.1.2

---

CHANGELOG.md
android/build.gradle
package.json

Upgrade mindbox mobile-sdk to v.2.1.2

Upgrade mindbox mobile-sdk to v.2.1.2

---

CHANGELOG.md
MindboxSdk.podspec
android/build.gradle
package.json
src/index.tsx

Add reinitialization feature
- Upgrade iOS SDK to v2.1.0
- Upgrade Android SDK to v2.1.3
- Remove reinitialization check

Reinitialization feature

---

CHANGELOG.md
MindboxSdk.podspec
android/build.gradle
package.json

- upgrade iOS SDK dependency to v2.1.1
- upgrade Android SDK dependency to v2.1.4

Upgrade native dependencies

---

CHANGELOG.md
android/build.gradle
package.json

- upgrade Android SDK dependency to v2.1.5

Upgrade android sdk to 2.1.5

---

CHANGELOG.md
MindboxSdk.podspec
package.json

- upgrade iOS SDK dependency to v2.1.2

Upgrade iOS SDK dependency to v2.1.2

---

CHANGELOG.md
android/build.gradle
package.json

- upgrade Android SDK dependency to v2.1.6

Upgrade android sdk to 2.1.6

---

CHANGELOG.md
android/build.gradle
package.json

- upgrade Android SDK dependency to v2.1.10

Upgrade Android SDK dependency to v2.1.10

---

README.md

https://github.com/mindbox-cloud/issues-web-mobile/issues/3120

MBX-3120: Updating README.md

---

ios/MindboxJsDelivery.m

https://github.com/mindbox-cloud/issues-web-mobile/issues/3383

MBX-3383: fix getting url from button for old notification format

---

example/exampleApp/android/app/build.gradle
example/exampleApp/android/app/src/main/AndroidManifest.xml
example/exampleApp/android/app/src/main/java/com/exampleapp/MainApplication.kt
example/exampleApp/android/app/src/main/java/com/exampleapp/MindboxFirebaseMessagingService.kt
example/exampleApp/android/app/src/main/java/com/exampleapp/MindboxHuaweiMessagingService.kt
example/exampleApp/android/app/src/main/java/com/exampleapp/NotificationModule.kt
example/exampleApp/android/app/src/main/java/com/exampleapp/NotificationPackage.kt
example/exampleApp/ios/AppDelegate.swift
example/exampleApp/ios/MindboxNotificationServiceExtension/NotificationService.swift
example/exampleApp/ios/Models/MindboxRemoteMessage.swift
example/exampleApp/ios/Models/PushAction.swift
example/exampleApp/ios/NotificationModule.m
example/exampleApp/ios/NotificationModule.swift
example/exampleApp/ios/exampleApp.xcodeproj/project.pbxproj
example/exampleApp/ios/exampleApp.xcodeproj/xcshareddata/xcschemes/exampleApp.xcscheme
example/exampleApp/package-lock.json
example/exampleApp/package.json
example/exampleApp/src/App.tsx
example/exampleApp/src/components/NotificationItem.tsx
example/exampleApp/src/components/NotificationItemStyle.ts
example/exampleApp/src/components/NotificationScreenStyles.ts
example/exampleApp/src/components/index.ts
example/exampleApp/src/screens/HomeScreen.tsx
example/exampleApp/src/screens/NotificationCenterScreen.tsx
example/exampleApp/src/utils/MindboxOperations.tsx
example/exampleApp/src/utils/Notification.tsx
example/exampleApp/src/utils/NotificationStub.tsx

https://github.com/mindbox-cloud/issues-web-mobile/issues/3471

MBX-3471: add NC example for android

---

android/src/main/java/com/mindboxsdk/MindboxSdkModule.kt
ios/MindboxSdk.m
ios/MindboxSdk.swift
src/index.tsx

https://github.com/mindbox-cloud/issues-web-mobile/issues/3363

MBX-3363: added public logging method

---

src/index.tsx

https://github.com/mindbox-cloud/issues-web-mobile/issues/3565

MBX-3565: deprecate pushDelivered method

---

android/src/main/java/com/mindboxsdk/MindboxJsDelivery.kt
src/index.tsx

https://github.com/mindbox-cloud/issues-web-mobile/issues/3644

MBX-3644: add logs for getting data from push

---

.github/workflows/build.yml

https://github.com/mindbox-cloud/issues-web-mobile/issues/3657

 Added running unit tests when opening a PR

---

.github/workflows/trigger-build-app.yml

[[Mobile] Привести версии пушков к версии SDK](https://github.com/mindbox-cloud/issues-web-mobile/issues/3617)

MBX-3617 Trigger script

---

example/exampleApp/android/app/src/main/java/com/exampleapp/MindboxHuaweiMessagingService.kt

https://github.com/mindbox-cloud/issues-web-mobile/issues/3675

MBX-3675: run handleRemoteMessage asynchronously in example

---

android/build.gradle

https://tracker.yandex.ru/WMSDK-391

WMSDK-391: bump minSdk version

---

example/exampleApp/android/build.gradle
example/exampleApp/android/gradle/wrapper/gradle-wrapper.properties
example/exampleApp/package.json

bump gradle version in example

example: bump gradle version

---

MindboxSdk.podspec
android/build.gradle
android/src/main/java/com/mindboxsdk/MindboxSdkModule.kt
example/exampleApp/android/app/build.gradle
example/exampleApp/android/app/src/main/AndroidManifest.xml
example/exampleApp/android/app/src/main/java/com/exampleapp/MainApplication.kt
example/exampleApp/android/app/src/main/java/com/exampleapp/MindboxRuStoreMessagingService.kt
example/exampleApp/android/build.gradle
example/exampleApp/ios/Podfile
example/exampleApp/ios/Podfile.lock
example/exampleApp/package.json
example/exampleApp/src/screens/HomeScreen.tsx
ios/MindboxSdk.m
ios/MindboxSdk.swift
package.json
src/__tests__/index.test.ts
src/index.tsx

https://tracker.yandex.ru/WMRUSTORE-38

WMRUSTORE-38: Add Rustore

---

CHANGELOG.md
MindboxSdk.podspec
android/build.gradle
package.json

Bump RN SDK versions: core=2.13.5-rc, android=2.13.5-rc, ios=2.13.5-rc
